services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hackathon-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MzansiMarket123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - hacknet

  webapp:
    build: .
    container_name: hackathon-web
    environment:
      ASPNETCORE_URLS: http://+:7229
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=MzansiMarketDB;User Id=sa;Password=MzansiMarket123!;TrustServerCertificate=True;"
    ports:
      - "7229:7229"
    depends_on:
      - db
    networks:
      - hacknet

volumes:
  mssql_data:

networks:
  hacknet:
